sudo: required
services:
  - docker
before_install:
  # update is required to update the repositories to see the new packages for
  # Docker.
  - sudo apt-get update

  - cd ${TRAVIS_BUILD_DIR}
  - git clone https://github.com/kongyew/greenplum-dockers.git
#  - cd greenplum-dockers

script:
    - cd ${TRAVIS_BUILD_DIR}/greenplum-dockers
    - cd gpdb
    - docker build --build-arg GPDB_VERSION="5.7.0"  -t "kochanpivotal/gpdb5oss" -f gpdb/DockerfileOpenSource .
    - docker run --interactive --tty -h gpdbsne "kochanpivotal/gpdb5oss" /bin/bash -c "/usr/local/bin/setupGPDB.sh -g /opt/gpdb;/usr/local/bin/stopGPDB.sh  -g /opt/gpdb"
  #  - docker commit -m "GPDB 5 OSS" -a "author" "kochan" "kochanpivotal/gpdb5oss"
    - ls -al
