sudo: required
services:
  - docker

script:
  - docker build --build-arg GPDB_VERSION="5.7.0"  -t "kochanpivotal/gpdb5oss" -f gpdb/DockerfileOpenSource .
  - docker run --interactive --tty -h gpdbsne "kochanpivotal/gpdb5oss" /bin/bash -c "/usr/local/bin/setupGPDB.sh -g /opt/gpdb;/usr/local/bin/stopGPDB.sh  -g /opt/gpdb"
  - docker commit -m "GPDB 5 OSS" -a "author" "kochan" "kochanpivotal/gpdb5oss"
after_script:
  - docker images


