version: '2'
services:
  namenode:
      image: gelog/hadoop
      ports:
          - "50070:50070"
      command: hdfs namenode
      container_name: hdfs-namenode

  datanode:
      image: gelog/hadoop
      command: hdfs datanode
      ports:
  # The host port is randomly assigned by Docker, to allow scaling to multiple DataNodes on the same host
          - "50075"
      links:
          - namenode:hdfs-namenode

  secondarynamenode:
      image: gelog/hadoop
      command: hdfs secondarynamenode
      ports:
          - "50090:50090"
      links:
          - namenode:hdfs-namenode
      volumes:
         - ..:/code
      tty: true
  gpdb5:
        #build:
        #  context: .
        #  dockerfile: ./gpdb/Dockerfile
        image: "kochan/gpdb5.1"
        command: bin/bash
        hostname: "gpdbsne"
        ports:
         - "5432:5432"
         - "5005:5005"
         - "5010:5010"
         - "9022:22"
         - "40000:40000"
         - "40001:40001"
         - "40002:40002"
        expose:
         - "5432"
        volumes:
         - ..:/code
        links:
         - namenode
         - datanode
         - secondarynamenode
        tty: true
