version: '3'
services:
  cloudera:
    image: cloudera/quickstart:latest
    command: /usr/bin/docker-quickstart
    #;/home/cloudera/cloudera-manager --express
    hostname: "quickstart.cloudera"
    container_name: quickstart.cloudera
    environment:
      - COMPOSE_HTTP_TIMEOUT=120 # default is 60
    ports:
      - "8020:8020"
      - "8022:22"     # ssh
      - "7180:7180"   # Cloudera Manager
      - "8888:8888"   # HUE - user/passwd   cloudera/cloudera
      - "11000:11000" # Oozie
      - "50070:50070" # HDFS REST Namenode
      - "2181:2181"
      - "11443:11443"
      - "9090:9090"
      - "8088:8088"
      - "19888:19888"
      - "9092:9092"
      - "8983:8983"
      - "16000:16000"
      - "16001:16001"
      - "42222:22"
      - "8042:8042"
      - "60010:60010"
      - "8080:8080"
      - "7077:7077"
      - "9080:80"
      - "10002:10002" # HIVESERVER2 Web UI
    volumes:
       - ..:/code
    tty: true
    privileged: true
    links:
         - gpdb5:gpdbsne
    networks:
      mynetwork:
        aliases:
          - quickstarter.cloudera
          - quickstarter.cloudera.localdomain.com
  gpdb5:
        #build:
        #  context: .
        #  dockerfile: ./gpdb/Dockerfile
        image: "kochanpivotal/gpdb5-pxf"
        command: bin/bash
        hostname: "gpdbsne"
        container_name: gpdbsne
        ports:
         - "5432:5432"
         - "5005:5005"
         - "5010:5010"
         - "9022:22"
         - "40000:40000"
         - "40001:40001"
         - "40002:40002"
        expose:
         - "5432"
        volumes:
         - ..:/code
        privileged: true
        tty: true
        networks:
          mynetwork:
            aliases:
              - gpdbsne
              - gpdbsne.localdomain.com
networks:
    mynetwork:
      driver: bridge
