sudo /home/cloudera/cloudera-manager --enterprise
# [QuickStart] Shutting down CDH services via init scripts...
# kafka-server: unrecognized service
# JMX enabled by default
# Using config: /etc/zookeeper/conf/zoo.cfg
# [QuickStart] Disabling CDH services on boot...
# error reading information on service kafka-server: No such file or directory
# [QuickStart] Starting Cloudera Manager server...
# [QuickStart] Waiting for Cloudera Manager API...
# [QuickStart] Starting Cloudera Manager agent...
# [QuickStart] Activating trial license for Enterprise...
# [QuickStart] Configuring deployment...
# Submitted jobs: 15
# [QuickStart] Deploying client configuration...
# Submitted jobs: 17
# [QuickStart] Starting Cloudera Management Service...
# Submitted jobs: 25
# [QuickStart] Enabling Cloudera Manager daemons on boot...
# ________________________________________________________________________________
# Success! You can now log into Cloudera Manager from the QuickStart VM's browser:
    # 
    # http://quickstart.cloudera:7180
    #
    # Username: cloudera
    # Password: cloudera
